### ISSUE TITLE
Easy and obvious custom project subdirectories

### ISSUE THREAD

**Issue by ahundt** [cmake-basis/legacy#305]
Right now there aren't easy or clear instructions for how to change the default subdirectories.

**Comment by schuhschuh** [comment]
These are all optional arguments of the `basis_project` command in the `BasisProject.cmake` file of the project, e.g., `CONFIG_DIR`, `CODE_DIR`, `EXAMPLE_DIR`,... You can add further custom subdirectories using the new `OTHER_DIRS` option. See [MIRTK BasisProject.cmake file](https://github.com/BioMedIA/MIRTK/blob/7045009da70cb8355610f5d3f9d8efe12a3bb0fd/BasisProject.cmake#L67) for an example usage in a project with custom directory names and layout that differs from the default. Changing this to a documentation task rather than a feature request.
