### ISSUE TITLE
Add function(s) which allow developers to selectively use target UIDs 

### ISSUE THREAD

**Issue by ahundt** [cmake-basis/legacy#438]
I created a toplevel repository with two modules that each have documentation, and the documentation code conflicts. The namespacing tools may fix this, but is there a reasonable way to fix this without them?

```
 CMake Error at /usr/local/share/basis/cmake-modules/CommonTools.cmake:1872 (message):
   There exists already a target named site.  Target names must be unique.
 Call Stack (most recent call first):
   /usr/local/share/basis/cmake-modules/TargetTools.cmake:524 (basis_check_target_name)
   modules/robone/doc/CMakeLists.txt:34 (basis_add_custom_target)
```

**Comment by schuhschuh** [comment]
Interesting, indeed if you'd enable target UIDs of BASIS, this should not happen. Just like you have to choose unique library target names, you will have to choose unique documentation target names. Edit the ```doc/CMakeLists.txt``` and include the module name in the target names.

**Comment by ahundt** [comment]
Yeah, I know that is the case but maybe we can think up a workaround?

**Comment by schuhschuh** [comment]
A workaround can either just be another implementation of the target UIDs (i.e., already done) or a change of the project template file doc/CMakeLists.txt.

**Comment by schuhschuh** [comment]
Now this is why I was never a big fan of the ```basisproject``` tool. If people had to write the CMake code in their own project themselves or at least copy and paste, then modify it, they would be more familiar with it and it should be quite obvious that the target names they then choose may create conflicts.

**Comment by ahundt** [comment]
Yeah I see what your saying, but on the other hand it should also be reasonable to name your target `doc` when it is standalone, but then another user may make it a module.

**Comment by schuhschuh** [comment]
Yes, but therefore the introduction of the target UIDs in BASIS. As we decided to deactivate this functionality, developers have to take care of such ambiguities themselves. Just like in the source code file or any other build targets. What does "doc" make it so special to treat it differently ? Why not apply the same then also to a "utils" or "common" library target ?

My point is that what you are asking for is already implemented. It's enabled by setting ```BASIS_USE_TARGET_UIDS=ON```. The reason for disabling it was performance. In this case it's up to the project/module developer to choose target names which reduce the risk of name conflicts. As is the case for plain CMake. The more functionality of the original BASIS is disabled, the more responsibility is on the developer again.

At the moment, I see only one compromise: To enable developers (or the project template files) to selectively make use of target UIDs in order to avoid expected conflicts such as in case of the documentation generation targets of the project template which is expected to be used by all modules. The target names can be modified to include already the project/module name as prefix.

I was thinking of adding a function such as ```basis_make_target_name``` which would be kind of opposite to the existing ```basis_make_target_uid```. If target UIDs are enabled, ```basis_make_target_name``` does nothing because ```basis_make_target_uid``` utilised by ```basis_add_*``` commands implicitly ensures unique target names. Otherwise, if target UIDs are disabled, ```basis_make_target_name``` can be used by developers to explicitly create prefixed target names because in that case ```basis_make_target_uid``` will actually do nothing.

```
if (BASIS_USE_TARGET_UIDS)
  function (basis_make_target_uid TARGET_UID TARGET_NAME)
    _basis_make_target_uid (UID "${TARGET_NAME}")
    set ("${TARGET_UID}" "${UID}" PARENT_SCOPE)
  endfunction ()
  function (basis_make_target_name TARGET_UID TARGET_NAME)
    if (TARGET_NAME MATCHES "^\\.+(.*)$")
      set ("${TARGET_UID}" "${CMAKE_MATCH_1}" PARENT_SCOPE)
    else ()
      set ("${TARGET_UID}" "${TARGET_NAME}" PARENT_SCOPE)
    endif ()
  endfunction ()
else ()
  function (basis_make_target_uid TARGET_UID TARGET_NAME)
    if (TARGET_NAME MATCHES "^\\.+(.*)$")
      set ("${TARGET_UID}" "${CMAKE_MATCH_1}" PARENT_SCOPE)
    else ()
      set ("${TARGET_UID}" "${TARGET_NAME}" PARENT_SCOPE)
    endif ()
  endfunction ()
  function (basis_make_target_name TARGET_UID TARGET_NAME)
    _basis_make_target_uid (UID "${TARGET_NAME}")
    set ("${TARGET_UID}" "${UID}" PARENT_SCOPE)
  endfunction ()
endif ()
```

This could be used in user CMake code as follows which works whether or not the target UID feature of BASIS is enabled or not. If the original target UIDs of BASIS are enabled, it would be obsolete boiler-plate code, though. If target UIDs are disabled, this would explicitly make use of them for this particular target.

```
basis_make_target_name(DOC doc)
basis_add_doc(${DOC} ...)
```

Now this would give the project developer (more or less) full control over the actual target names while still asking BASIS to construct a unique name. Personally, I think the better solution were the target UIDs in the first place, however.

Maybe this idea can be taken further by making the option ```BASIS_USE_TARGET_UIDS``` not just a global option, but instead allow developers to enable/disable this feature at any time, i.e.,
```
basis_enable_target_uids()
basis_add_doc(doc ...)
basis_add_library(common ...)
basis_disable_target_uids()
basis_add_library(fooutils ...)
```
which, assuming project name "Foo", would add targets with the following names:
- foo.doc
- foo.common
- fooutils
